# Generated by Django 2.1.5 on 2019-03-10 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('food_details', models.CharField(max_length=1000)),
                ('food_availability', models.BooleanField(default=True)),
                ('cost', models.IntegerField(default=0)),
                ('food_img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant_admin.Food')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=1000)),
                ('takeaway', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.IntegerField(primary_key=True, serialize=False)),
                ('table_availability', models.BooleanField(default=True)),
                ('table_readyornot', models.BooleanField(default=True)),
                ('reservation_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=3, verbose_name={'CA': 'Cashier', 'CH': 'Chef', 'MCH': 'Master Chef', 'W': 'Waiter'})),
                ('home_addr', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='0(21|26|25|86|24|23|81|28|31|44|11|74|83|51|45|17|41|54|87|71|66|34|56|13|77|76|61|38|58|35|84)[0-9]+')])),
                ('mobile_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="your number isn't correct.\n                                        true formats :\n                                        1) +989999999999 2)09999999999", regex='^(\\+98|0)?9\\d{9}')])),
                ('profile', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderList_Table', to='restaurant_admin.Table'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FoodOrder_order', to='restaurant_admin.OrderList'),
        ),
        migrations.AddField(
            model_name='food',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food_FoodCategory', to='restaurant_admin.FoodCategory'),
        ),
    ]
