# Generated by Django 2.1.5 on 2019-03-10 12:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_birthdate', models.DateField()),
                ('sub_address', models.CharField(max_length=1000)),
                ('sub_phone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='0(21|26|25|86|24|23|81|28|31|44|11|74|83|51|45|17|41|54|87|71|66|34|56|13|77|76|61|38|58|35|84)[0-9]+')])),
                ('sub_mobile_phone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="your number isn't correct.\n                                        true formats :\n                                        1) +989999999999 2)09999999999", regex='^(\\+98|0)?9\\d{9}')])),
            ],
        ),
    ]
